    - name: Build APK with Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25b
        export ANDROID_HOME=/usr/local/lib/android/sdk

        # Автоматически принимаем все лицензии Android SDK, чтобы пакеты не сбрасывались
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

        # Принудительно устанавливаем build-tools 33.0.2 через sdkmanager с автопринятием
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2" "platforms;android-33"

        # Прописываем версию 33.0.2 прямо в спек
        sed -i 's/^#* *android.build_tools_version.*/android.build_tools_version = 33.0.2/g' buildozer.spec
        sed -i 's/^#* *android.api.*/android.api = 33/g' buildozer.spec
        sed -i 's/^#* *android.min_api.*/android.min_api = 21/g' buildozer.spec

        buildozer -v android debug
