name: Build Lord App APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer Action
        uses: ArtemShedov/buildozer-action@v1.2
        with:
          command: buildozer -v android debug
          repository_root: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LordApp-APK
          path: bin/*.apk
