    - name: Build APK with Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25b
        export ANDROID_HOME=/usr/local/lib/android/sdk

        # Заготовка лицензий
        mkdir -p $ANDROID_HOME/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fb5" > $ANDROID_HOME/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a648b0" >> $ANDROID_HOME/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" >> $ANDROID_HOME/licenses/android-sdk-preview-license

        # Ставим компоненты
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

        # Закольцовываем версии в спек-файле
        sed -i 's/^#* *android.build_tools_version.*/android.build_tools_version = 33.0.2/g' buildozer.spec
        sed -i 's/^#* *android.api.*/android.api = 33/g' buildozer.spec
        sed -i 's/^#* *android.min_api.*/android.min_api = 21/g' buildozer.spec

        # КОЛЬЦЕВАЯ ИЗОЛЯЦИЯ:
        # Уничтожаем любые попытки Buildozer создать свою пустую зону и замыкаем его на системный SDK по кругу
        mkdir -p ~/.buildozer/android/platform/
        rm -rf ~/.buildozer/android/platform/android-sdk
        
        # Создаем кольцо симлинков
        ln -s $ANDROID_HOME ~/.buildozer/android/platform/android-sdk

        # Дополнительно замыкаем build-tools внутри самого системного SDK на случай запросов других версий (37.0.0 и т.д.)
        cd $ANDROID_HOME/build-tools
        if [ -d "33.0.2" ] && [ ! -e "37.0.0" ]; then
          ln -s 33.0.2 37.0.0
        fi
        cd -

        # Запуск сборки в замкнутом контуре
        buildozer -v android debug
